name: charts_flutter_plus_example
description: Demonstrates how to use the charts_flutter_plus plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  charts_flutter_plus:
    path: ../

  cupertino_icons: ^1.0.2

  flutter_test:
    sdk: flutter
  meta: ^1.1.1
  intl: ^0.18.1

dev_dependencies:
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
