name: charts_flutter_plus
description: Material Design charting library for flutter.
version: 0.0.1
homepage: https://github.com/google/charts
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  charts_common:
    git:
      url: https://github.com/Project112224/charts_flutter_plus
      path: charts_common
      ref: main

  collection: ^1.17.2
  intl: ^0.18.1
  logging: ^1.2.0
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  mockito: ^5.4.2
  build_runner: ^2.4.6
  test: ^1.24.3

flutter:

  plugin:
    platforms:
      android:
        package: com.example.charts_flutter_plus
        pluginClass: ChartsFlutterPlusPlugin
      ios:
        pluginClass: ChartsFlutterPlusPlugin
